# see: https://terraform-docs.io/user-guide/configuration/version
version: ">= 0.15"

# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table

# see: https://terraform-docs.io/user-guide/configuration/header-from
header-from: header.md

# see: https://terraform-docs.io/user-guide/configuration/footer-from
footer-from: footer.md

# # see: https://terraform-docs.io/user-guide/configuration/recursive
# recursive:
#   enabled: true
#   path: modules

# see: https://terraform-docs.io/user-guide/configuration/sections
sections:
  show:
    - header
    - footer
    - inputs
    - modules
    - outputs
    - providers
    - requirements
    - resources

# see: https://terraform-docs.io/user-guide/configuration/content
content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}
  For a complete list of inputs and their descriptions for the Proxmox provider, refer to the [Proxmox Provider Documentation](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs).

  {{ .Outputs }}

  #### Usage
  ```hcl
  {{ include "examples/main.tf" }}
  ```  

  {{ .Footer }}

# see: https://terraform-docs.io/user-guide/configuration/output
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

# see: https://terraform-docs.io/user-guide/configuration/sort
sort:
  enabled: true
  by: required

# # https://terraform-docs.io/user-guide/configuration/output-values/
# output-values:
#   enabled: false
#   from: ""

# see: https://terraform-docs.io/user-guide/configuration/settings
settings:
  anchor: true
  color: true
  default: false
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 4
  lockfile: true
  read-comments: true
  required: false
  sensitive: true
  type: true